import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz
import requests

# ==========================================
# --- GITHUB CRR VAULT CONNECTION ---
# ==========================================
# ⚠️ ACTION REQUIRED: Replace this URL with your raw GitHub JSON link once uploaded
GITHUB_VAULT_URL = "https://raw.githubusercontent.com/YOUR_USERNAME/YOUR_REPO/main/market_state.json"

@st.cache_data(ttl=60) # Caches for 60 seconds to prevent spamming GitHub API
def load_vault_data():
    try:
        response = requests.get(GITHUB_VAULT_URL)
        if response.status_code == 200:
            return response.json()
        return None
    except:
        return None

# ==========================================
# --- INSTITUTIONAL UI THEME INJECTION ---
# ==========================================
st.set_page_config(page_title="VRP Quant | V22.2 Cloud", layout="wide", page_icon="🏦")
est_tz = pytz.timezone('US/Eastern')

try:
    USERS = st.secrets["credentials"]
except Exception as e:
    st.error("⚠️ SYSTEM LOCKED: Security vault not connected. Please configure [credentials] in Streamlit Secrets.")
    st.stop()

DISCLAIMER_TEXT = """**SEC MARKETING RULE (17 CFR § 275.206(4)-1) & REGULATORY COMPLIANCE NOTICE**
1. **Hypothetical Performance:** Metrics generated by this software are hypothetical and not guarantees of future results.
2. **Not Financial Advice:** VRP Quant provides quantitative data analysis for informational purposes only.
3. **Risk Disclosure:** Options trading involves substantial risk of loss."""

# ==========================================
# --- LOGIN & AUTHENTICATION ---
# ==========================================
def check_login():
    if "authenticated" not in st.session_state:
        st.session_state.authenticated = False
        st.session_state.tier = None
    if not st.session_state.authenticated:
        st.markdown("## 🔒 VRP Quant Terminal Login")
        c1, c2 = st.columns([1, 2])
        with c1:
            user = st.text_input("Username", key="login_u")
            pwd = st.text_input("Password", type="password", key="login_p")
            if st.button("Login"):
                if user in USERS and USERS[user]["password"] == pwd:
                    st.session_state.authenticated = True
                    st.session_state.tier = USERS[user]["tier"]
                    st.rerun()
                else: 
                    st.error("Invalid Credentials")
        st.markdown("---")
        st.markdown("### 👑 Founding Member Cohort (Beta)")
        st.caption("Institutional pricing is $299/mo (Analyst) and $999/mo (God Mode). Join the Private Beta today to lock in your lifetime discounted rate.")
        b1, b2 = st.columns(2)
        with b1:
            st.info("**ANALYST TIER**\n* Retail Price: ~~$299/mo~~\n* Founding Member: **$149/mo**")
            st.link_button("Subscribe ($149/mo)", "https://vrpquant.substack.com/subscribe", use_container_width=True)
        with b2:
            st.success("**GOD MODE TIER**\n* Retail Price: ~~$999/mo~~\n* Founding Member: **$499/mo**")
            st.link_button("Subscribe ($499/mo)", "https://vrpquant.substack.com/subscribe", use_container_width=True)
        st.markdown("---")
        st.success("🛡️ SEC Compliance Check: System verified.")
        st.caption(DISCLAIMER_TEXT)
        return False
    return True

# ==========================================
# --- MAIN APP EXECUTION ---
# ==========================================
if check_login():
    tier = st.session_state.tier
    
    # 1. FETCH CLOUD DATA
    vault_state = load_vault_data()
    
    with st.sidebar:
        st.markdown("# 🏦 VRP Quant V22.2")
        if tier == "GOD_MODE": st.success("🔓 GOD MODE ACTIVE")
        else: st.warning("🔒 ANALYST TIER")
        st.markdown("---")
        mode = st.sidebar.radio("Module", ["🚀 Market Scanner", "🔬 Deep Dive Analysis"])
        
        st.markdown("---")
        if vault_state:
            st.caption(f"📡 Vault Last Synced: {vault_state.get('last_updated', 'Unknown')}")
        else:
            st.error("📡 Vault Connection Severed")
            
        if st.button("Log Out"):
            st.session_state.authenticated = False
            st.rerun()

    if not vault_state:
        st.error("⚠️ Unable to connect to GitHub CRR Vault. The backend engine may be offline.")
        st.stop()

    df_scan = pd.DataFrame(vault_state["data"])

    # --- MODULE 1: MARKET SCANNER ---
    if mode == "🚀 Market Scanner":
        st.title("🚀 Institutional Market Scanner")
        st.caption(f"⏱️ **Data Snapshot:** Displaying latest compiled quantitative run from the cloud.")
        
        if tier != "GOD_MODE":
            st.error("🔒 ACCESS DENIED: Market Scanner is locked for Analyst Tier.")
        else:
            # Display a clean, filtered view of the dataframe
            display_cols = ["Ticker", "Price", "Alpha Score", "Trend", "VRP Edge", "Vol", "Strategy", "Kelly"]
            st.dataframe(df_scan[display_cols], use_container_width=True)

    # --- MODULE 2: DEEP DIVE ANALYSIS ---
    elif mode == "🔬 Deep Dive Analysis":
        st.title("🔬 Deep Dive & Trade Architect")
        st.caption(f"⏱️ **Data Vault Timestamp:** {vault_state.get('last_updated', 'N/A')}")
        
        # User selects from tickers available in the Vault
        available_tickers = df_scan['Ticker'].tolist()
        ticker = st.selectbox("Select Asset from Vault", available_tickers)
        
        if st.button("Run Analysis"):
            with st.spinner("Decrypting Institutional Vaults..."):
                stats = df_scan[df_scan['Ticker'] == ticker].iloc[0]

                st.markdown("### 📊 Market Variables")
                m1, m2, m3, m4, m5 = st.columns(5)
                m1.metric("Price", f"${stats['Price']:.2f}")
                m2.metric("Alpha Score", f"{stats['Alpha Score']}/100")
                m3.metric("Trend", stats['Trend'])
                m4.metric("Volatility", f"{stats['Vol']}")
                m5.metric("Trend Reversal", stats.get('Reversal', 'No Active Reversal'))

                m6, m7, m8, m9, m10 = st.columns(5)
                m6.metric("VRP Edge", stats['VRP Edge'])
                m7.metric("Sharpe Ratio", f"{stats.get('Sharpe', 'N/A')}")
                m8.metric("Support (Floor)", f"${stats['Support']:.2f}")
                m9.metric("Resistance (Ceiling)", f"${stats['Resistance']:.2f}")
                m10.metric("95% VaR (Variance)", f"${stats.get('VaR', 'N/A')}" if tier == "GOD_MODE" else "🔒 God Mode")

                st.markdown("### ⚙️ Strategy Backtest Validation (2-Year)")
                b1, b2, b3, b4, b5 = st.columns(5)
                b1.metric("Historical Win Rate", f"{stats['Win Rate']}")
                b2.metric("Net Strategy Return", f"{stats['Strat Ret']}")
                b3.metric("Alpha Generated", f"{stats['Outperf']}")
                b4.metric("Max DD", f"{stats['Max DD']}", delta_color="inverse" if tier == "GOD_MODE" else "normal")
                b5.metric("Kelly Fraction", f"{stats['Kelly']}", delta_color="normal")

                st.markdown("### 🎯 Optimal Trade Architecture")
                st.info(f"**STRATEGY:** {stats['Strategy']} | **LEGS:** {stats['Legs']}")
                s1, s2, s3 = st.columns(3)
                s1.metric("Est. Execution Target", stats['Premium'])
                s2.metric("Prob. of Profit (POP)", f"{stats['POP']}%")
                s3.metric("Ideal DTE", "30 Days")
                
                # Plotly Chart using cached data from the JSON
                if 'Chart_Dates' in stats and 'Chart_Prices' in stats:
                    fig = go.Figure()
                    fig.add_trace(go.Scatter(x=stats['Chart_Dates'], y=stats['Chart_Prices'], name='History', line=dict(color='white')))
                    
                    if 'MC_Projection' in stats:
                        # If the backend sent monte carlo projections
                        future_dates = pd.date_range(start=stats['Chart_Dates'][-1], periods=30, freq='B')
                        fig.add_trace(go.Scatter(x=future_dates, y=stats['MC_Projection'], name='Mean Projection', line=dict(dash='dash', color='orange')))
                        
                    fig.add_hline(y=stats['Support'], line_dash="dot", line_color="green", annotation_text="Support")
                    fig.add_hline(y=stats['Resistance'], line_dash="dot", line_color="red", annotation_text="Resistance")
                    fig.update_layout(template="plotly_dark", height=500, title="Institutional Chart (Pre-calculated in Engine)")
                    st.plotly_chart(fig, use_container_width=True)
                else:
                    st.warning("Chart data not provided by backend engine yet.")